name: Deploy Service Agent
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.28.0
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'pnpm'
    - run: pnpm install --ignore-scripts

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.28.0
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm publish --access public --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - uses: actions/setup-node@v2
      with:
        registry-url: https://npm.pkg.github.com/
    - run: pnpm publish --access public --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}